### ISSUE TITLE
Click to follow player as spectator has too many false positives

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet#10248]
In zCatch I lose focus of my killer every time. Because before I die I spam my mouse.
When I use the mouse to tab into the game I always start following a tee.

The first click into the window should be ignored. And ideally also a short delay after getting killed.

**Comment by dropalways** [comment]
cl_spectator_mouseclicks 0

**Comment by ChillerDragon** [comment]
> cl_spectator_mouseclicks

That fully deactivates it as far as I can tell. It is a good feature I loved using it in 0.7 and F-DDrace before ddnet had it. But recently the false positives started to annoy me. I think zCatch was already mentioned somewhere. I might be a rare mouse tabber but it should still be supported to not register clicking into the window as an in game action.

**Comment by dropalways** [comment]
> I might be a rare mouse tabber but it should still be supported to not register clicking into the window as an in game action.

Agreed, This should be fixed.

**Comment by KebsCS** [comment]
#9733

**Comment by ChillerDragon** [comment]
> [#9733](https://github.com/ddnet/ddnet/pull/9733)

Open since feb! 🙈 
But that does not fix clicking into ddnet when it was not the active window. Only the zCatch issue.

**Comment by ChillerDragon** [comment]
Ass rossbit pointed out correctly on discord. Clicking into the window does not get interpreted as in game click. I don't really know how I always end up following someone on kog then. Maybe I do too many random clicks. No idea how to fix that. So for now I would say https://github.com/ddnet/ddnet/pull/9733 fully covers this issue.

**Comment by ChillerDragon** [comment]
Oh wait I could reproduce.

https://github.com/user-attachments/assets/a4331c50-9f59-4e57-9d05-c5a845ff0771

**Comment by ChillerDragon** [comment]
Okay I found the consistent way to reproduce. Also tested with pure ddnet on master branch to be sure its not my fork.
I play on gnome 48.1 with ``gfx_fullscreen 3`` When the game is active and I tab into a window on the second screen (my browser for example). Then press super key to see all open tabs and click into the game. That click is setting the spectator. And that is actually a frequent move for me.

**Comment by heinrich5991** [comment]
> Okay I found the consistent way to reproduce. Also tested with pure ddnet on master branch to be sure its not my fork.
> I play on gnome 48.1 (X11) with `gfx_fullscreen 3` When the game is active and I tab into a window on the second screen (my browser for example). Then press super key to see all open tabs and click into the game. That click is setting the spectator. And that is actually a frequent move for me.

This seems like a different issue than the issue title. Can you update the issue title to this problem or open another issue for this problem? Clicks to go into a window being interpreted as clicks inside the window is a different bug.
