### ISSUE TITLE
remove hack

### ISSUE THREAD

**Issue by H-M-H** [ddnet/ddnet#377]
#359

make this better / have a look at official teeworlds repo

**Comment by PathosEthosLogos** [comment]
I think this is resolved.

**Comment by def-** [comment]
How so?

**Comment by H-M-H** [comment]
I am not sure but rather put this as reminder as @heinrich5991 considered this as a hackish solution. Maybe he can help here.

**Comment by PathosEthosLogos** [comment]
I think this is resolved with the vanilla client being updated to 0.6.3, as with DDNet is updated with it.

**Comment by necropotame** [comment]
I close it. If @heinrich5991 estimates that it's not fixed, he can open it again :)
