### ISSUE TITLE
Map not showing up as already finished in server browser

### ISSUE THREAD

**Issue by murpii** [ddnet/ddnet#4092]
Map: run_experience_of_incredibleness

![89puRIKYLv](https://user-images.githubusercontent.com/60477660/129628558-645ad5bb-5089-4942-b7d8-568b7405e129.png)

**Comment by gerdoe-jr** [comment]
Does DB update that fast?

**Comment by def-** [comment]
yes, should be. is it working now or still missing?

**Comment by def-** [comment]
Should be fixed. Reopen if not.

**Comment by murpii** [comment]
@def- this issue still persists, I don't think I can re-open this issue myself

**Comment by def-** [comment]
The map name is too long, so the server only sends part of it to client, I'll provide a fix.

**Comment by murpii** [comment]
Thanks :)
