### ISSUE TITLE
Mouse moves faster than cursor when moving

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet#4292]
in editor. Reported by cheeser0613 on Discord

https://user-images.githubusercontent.com/2335377/140338651-a7467931-305e-40ff-a003-5164e52cf381.mp4

@Jupeyy you changed something about mouse movement in editor, right?

**Comment by Jupeyy** [comment]
yes, i made it as fast as the menu

But both versions look wrong to me anyway, and this was also the behavior before

**Comment by archimede67** [comment]
@Robyt3 I think this is solved? I don't think I can reproduce the issue.

**Comment by Robyt3** [comment]
It still happens when you enable Zoom in the editor toolbar if I understand the original issue correctly. Doesn't look like the Zoom feature was available when this issue was opened though.

**Comment by archimede67** [comment]
Even with Zoom enabled, it seems like I can't reproduce that issue. Maybe am I doing something wrong?

https://github.com/ddnet/ddnet/assets/13364635/d743282e-0d8f-4d65-8c6f-0240350f2756

**Comment by Robyt3** [comment]
Seems like you also need to have selected a quads layer. It works correctly when a tiles layer is selected or when Zoom is disabled.

**Comment by archimede67** [comment]
Oh yeah, selecting a quads layer and enabling zoom is the issue. But it's different from the original issue though, as in the video only the game layer is selected.

**Comment by archimede67** [comment]
I'm not sure what should the "Zoom" function be doing:
- only zoom the quads
- zoom both quads and tile layers, preventing manual zoom in/out

If you select a quads layer and enable zoom, then zoom to the default in-game zoom value (I assume), then it works correctly.

**Comment by Robyt3** [comment]
Seems fine to me like it is if nobody complains about it. The tooltip `Toggles preview of how layers will be zoomed in-game` for the zoom feature could be updated slightly to make it more clear (`layers` --> `quad layers`).
