### ISSUE TITLE
Serverbrowser unusable with invalid communities JSON

### ISSUE THREAD

**Issue by heinrich5991** [ddnet/ddnet#7494]
> [12:33 AM]murpi: Nightly build seems to be broken:
> ![image](https://github.com/ddnet/ddnet/assets/366230/6d7af8e6-4b02-49aa-8aae-e63be4e31ef4)
> [12:33 AM]murpi: 0/970 Servers, with no filters applied

**Comment by def-** [comment]
I believe this is fixed already by https://github.com/ddnet/ddnet/pull/7493?

**Comment by Robyt3** [comment]
Yes, it's fixed in the next nightly, the change didn't make it into the current one.

**Comment by heinrich5991** [comment]
The server browser should still not be empty if you get an invalid communities object from there. It says "0/970 servers", even though no filters are applied.
